version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(levelname)s] [%(asctime)s] %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true
    access:
      propagate: true

  apscheduler.executors.default:
      propagate: false

root:
  level: INFO
  handlers: [console]
  propagate: no